# configuration settings for controller_manager for various controllers
controller_manager:
  # ros2 settings
  ros__parameters:
    update_rate: 30 # hz which controllers are updated
    use_sim_time: True # use simulation time

    diff_cont: # diff drive controller configuration
      type: diff_drive_controller/DiffDriveController # ros2 diff drive controller

    joint_broad: # joint state controller configuration
      type: joint_state_broadcaster/JointStateBroadcaster

# configuration settings for differential drive controller "diff_control"
diff_cont:
  ros__parameters:

    publish_rate: 50.0 # hz, N messages per second

    # reference frame for robot base
    base_frame_id: base_link # usually the moving part
    # reference frame for the odometry information
    odom_frame_id: "odom" # tracks position relative to start

    # joint names
    left_wheel_names: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'back_right_wheel_joint']
    wheel_separation: 0.188
    wheel_radius: 0.0325

    use_stamped_vel: false # if controller should use a timstamped velocity command
    