velodyne:  
  frame_id: velodyne  
  lasers:    
    - dist_correction: 0.0      
      dist_correction_x: 0.0      
      dist_correction_y: 0.0      
      focal_distance: 0.0      
      focal_slope: 0.0      
      horiz_offset_correction: 0.0      
      laser_id: 0      
      rot_correction: 0.0      
      vert_correction: -0.2617993877991494      
      vert_offset_correction: 0.0  
  num_lasers: 16  
  distance_resolution: 0.002